/**
 * Instructions for the local LLM when mapping project descriptions to ForePath line items.
 * Keep rules explicit — small models otherwise over-use travel and under-estimate software scope.
 */
export const FOREPATH_ESTIMATE_CALCULATION_GUIDELINES = [
  'Estimation rules:',
  '',
  'Billing units:',
  '- One billing unit = 15 minutes of work (4 units = 1 hour).',
  '- consulting, it-systems, and software-development line items MUST include billingUnits.',
  '- travel-km and travel-long line items MUST include quantity; travel-short is a single flat rate.',
  '',
  'Choose the right service:',
  '- Custom applications, APIs, integrations, web/mobile apps → software-development.',
  '- Discovery, architecture, compliance workshops, delivery planning → consulting.',
  '- Ongoing ops, hosting support, infrastructure runbooks → it-systems (not for greenfield app builds).',
  '- Travel services are ONLY for physical on-site presence. Never use travel as a substitute for development effort.',
  '',
  'Travel (strict):',
  '- Default to ZERO travel line items. ForePath delivers software remotely unless the user explicitly requests on-site work.',
  '- Include travel only when the user mentions on-site meetings, installation at their premises, field work, or travel to a location.',
  '- Do not invent long-distance travel for software-only projects.',
  '- If travel is omitted, state that in assumptions.',
  '',
  'Sizing software-development (use these DEFAULT billingUnits when scope matches; only deviate if the user explicitly says minimal/simple or complex/enterprise):',
  '- Tiny fix, script, or single endpoint: 48 units (12 hours).',
  '- Small web feature or internal tool: 160 units (40 hours).',
  '- Single-platform web MVP (auth, CRUD, admin basics): 520 units (130 hours).',
  '- Complex web app (maps/GIS, realtime, search workflows, multiple user roles, third-party APIs): 1600 units.',
  '- Additional native mobile platform (iOS or Android): 800 units per platform for an MVP of similar scope.',
  '- Multi-platform delivery (web + iOS + Android) for a non-trivial product: sum the defaults above; do not invent ad-hoc totals.',
  '',
  'Sizing consulting (discovery, architecture, and advisory engagements):',
  '- Short advisory session or introductory workshop: 48 units (12 hours).',
  '- Focused workshop, review, or planning session: 160 units (40 hours).',
  '- Single-domain discovery with roadmap delivery: 520 units (130 hours).',
  '- Multi-domain or enterprise consulting program (cloud, security, DevOps, AI, infrastructure): 1600 units.',
  '',
  'Sizing it-systems (managed IT and operational support):',
  '- One-off fix or small operational task: 48 units (12 hours).',
  '- Focused support in one IT area (network, backup, workstations, M365, etc.): 160 units (40 hours).',
  '- Managed scope across multiple IT areas or ongoing monthly operations: 520 units (130 hours).',
  '- Broad managed IT coverage across many operational domains: 1600 units.',
  '- Use rateTier emergency-week or emergency-sunday only when the user explicitly requests urgent or out-of-hours support.',
  '',
  'Deterministic output:',
  '- Use the default billingUnits above unless the user explicitly qualifies scope as minimal or maximal.',
  '- Round all billingUnits to the nearest multiple of 4 (whole hours).',
  '- List line items in this order: consulting, it-systems, software-development, travel-km, travel-short, travel-long.',
  '- Use the same line item structure for the same scope description; do not randomly split or merge items.',
  '',
  'Complexity signals that INCREASE development units:',
  '- Multiple distinct user roles or admin interfaces.',
  '- Map or geospatial features, custom overlays, or grid/quadrant search logic.',
  '- Public-facing and staff-facing apps.',
  '- Regulatory or legal compliance (e.g. German data protection and sector rules) → add consulting for analysis; development must still reflect implementation effort.',
  '- Realtime coordination, duplicate-check workflows, or mission-critical UX.',
  '',
  'Line item structure:',
  '- Prefer several software-development lines by major scope (e.g. backend/API, web app, mobile apps) instead of one tiny development line plus large travel.',
  '- Development line items should usually represent the majority of the subtotal for software projects.',
  '- Use assumptions for uncertainty (phasing, exact platform parity, compliance depth).',
  '- Set confidence to "low" when scope is broad or compliance is mentioned without detail.',
].join('\n');

export const FOREPATH_ESTIMATE_CALCULATION_GUIDELINES_COMPACT = [
  'Estimation rules (follow exactly):',
  '',
  'Billing units:',
  '- One billing unit = 15 minutes (4 units = 1 hour).',
  '- consulting, it-systems, and software-development MUST include billingUnits.',
  '- travel-km and travel-long MUST include quantity; travel-short is flat rate.',
  '',
  'Service mapping:',
  '- Custom apps, APIs, integrations, web/mobile apps → software-development (REQUIRED for any app or platform build).',
  '- Workshops, discovery, architecture, compliance planning → consulting.',
  '- Ongoing ops/hosting support → it-systems (not greenfield builds).',
  '- Never substitute consulting or travel for missing software-development effort.',
  '',
  'Travel (strict):',
  '- Default to ZERO travel line items unless the user explicitly requests on-site work.',
  '- Never substitute travel for missing development effort.',
  '',
  'Default software-development billingUnits (use unless user says minimal/simple or complex/enterprise):',
  '- Tiny fix, script, or single endpoint: 48 units.',
  '- Small web feature or internal tool: 160 units.',
  '- Single-platform web MVP (auth, CRUD, admin basics): 520 units.',
  '- Complex web app (maps/GIS, realtime, search, multiple roles, third-party APIs): 1600 units.',
  '- Additional native mobile platform: 800 units per platform.',
  '- Multi-platform delivery: sum the defaults above.',
  '',
  'Default consulting billingUnits:',
  '- Short advisory session: 48 units.',
  '- Focused workshop or review: 160 units.',
  '- Discovery with roadmap for one domain: 520 units.',
  '- Multi-domain consulting program: 1600 units.',
  '',
  'Default it-systems billingUnits:',
  '- One-off operational task: 48 units.',
  '- Single IT area support: 160 units.',
  '- Multi-area managed IT or ongoing ops: 520 units.',
  '- Broad managed IT coverage: 1600 units.',
  '',
  'Deterministic output:',
  '- Round billingUnits to multiples of 4.',
  '- Order line items: consulting, it-systems, software-development, travel-km, travel-short, travel-long.',
  '- Development line items must dominate the subtotal for software projects.',
  '- Use assumptions for uncertainty; set confidence to low when scope is broad.',
].join('\n');

export const FOREPATH_ESTIMATE_JSON_SCHEMA_DESCRIPTION = [
  '{',
  '  "summary": string,',
  '  "lineItems": [',
  '    {',
  '      "serviceId": "consulting" | "it-systems" | "software-development" | "travel-km" | "travel-short" | "travel-long",',
  '      "description": string,',
  '      "billingUnits": number (required for consulting, it-systems, software-development),',
  '      "quantity": number (required for travel-km and travel-long),',
  '      "rateTier": "standard" | "emergency-week" | "emergency-sunday" (only for it-systems)',
  '    }',
  '  ],',
  '  "assumptions": string[],',
  '  "confidence": "low" | "medium" | "high"',
  '}',
].join('\n');
