import { Route } from '@angular/router';
import {
  AdminBillingFacade,
  AdminCustomerProfilesFacade,
  AdminInvoiceManagerFacade,
  adminCustomerProfilesReducer,
  adminInvoiceManagerReducer,
  adminMarkPaid$,
  adminMarkUnpaid$,
  adminVoidInvoice$,
  adminInvoiceManagerMarkPaid$,
  adminInvoiceManagerMarkUnpaid$,
  adminInvoiceManagerVoid$,
  createAdminCustomerProfile$,
  createManualInvoice$,
  deleteAdminCustomerProfile$,
  deleteManualInvoice$,
  issueManualInvoice$,
  loadAdminCustomerProfiles$,
  loadAdminCustomerProfilesBatch$,
  loadAdminInvoiceManager$,
  loadAdminInvoiceManagerBatch$,
  updateAdminCustomerProfile$,
  updateManualInvoice$,
  adminBillingReducer,
  billNow$,
  loadAdminAuditLogs$,
  loadAdminBillingSummary$,
  loadAdminOpenOverdue$,
  loadAdminStatisticsByProduct$,
  loadAdminStatisticsSummary$,
  AvailabilityFacade,
  availabilityReducer,
  BackordersFacade,
  backordersReducer,
  billingDashboardSocketApplicationErrorFallback$,
  BillingDashboardSocketFacade,
  billingDashboardSocketReducer,
  cancelBackorder$,
  cancelSubscription$,
  checkAvailability$,
  checkAvailabilityAlternatives$,
  connectBillingDashboardSocket$,
  connectBillingDashboardSocketFailureFallback$,
  createInvoice$,
  createServicePlan$,
  createServiceType$,
  createSubscription$,
  CustomerProfileFacade,
  customerProfileReducer,
  deleteServicePlan$,
  deleteServiceType$,
  disconnectBillingDashboardSocket$,
  InvoicesFacade,
  invoicesReducer,
  loadBackorders$,
  loadBackordersBatch$,
  loadCustomerProfile$,
  loadInvoices$,
  loadInvoicesSummary$,
  loadInvoiceDetails$,
  loadOpenOverdueInvoices$,
  reloadInvoicesAfterCreate$,
  initiatePaymentRedirect$,
  loadOverviewServerInfo$,
  loadProviderDetails$,
  loadServicePlan$,
  loadServicePlans$,
  loadServicePlansBatch$,
  loadServiceType$,
  loadServiceTypes$,
  loadServiceTypesBatch$,
  loadSubscription$,
  loadSubscriptions$,
  loadSubscriptionsBatch$,
  previewPricing$,
  restartServer$,
  resumeSubscription$,
  retryBackorder$,
  ServicePlansFacade,
  servicePlansReducer,
  ServiceTypesFacade,
  serviceTypesReducer,
  startServer$,
  stopServer$,
  SubscriptionServerInfoFacade,
  subscriptionServerInfoReducer,
  SubscriptionsFacade,
  subscriptionsReducer,
  updateCustomerProfile$,
  updateServicePlan$,
  updateServiceType$,
} from '@forepath/agenstra/frontend/data-access-billing-console';
import { authGuard, identityAuthProviders, identityAuthRoutes } from '@forepath/identity/frontend';
import { provideEffects } from '@ngrx/effects';
import { provideState } from '@ngrx/store';

import { AdminBillingPageComponent } from './admin-billing-page/admin-billing-page.component';
import { AdminCustomerProfilesPageComponent } from './admin-customer-profiles-page/admin-customer-profiles-page.component';
import { BillingConsoleContainerComponent } from './container/container.component';
import { billingAdminGuard } from './guards/billing-admin.guard';
import { InvoicesComponent } from './invoices/invoices.component';
import { OverviewComponent } from './overview/overview.component';
import { ServicePlansPageComponent } from './service-plans-page/service-plans-page.component';
import { ServiceTypesPageComponent } from './service-types-page/service-types-page.component';
import { SubscriptionsComponent } from './subscriptions/subscriptions.component';

export const billingConsoleRoutes: Route[] = [
  {
    path: '',
    component: BillingConsoleContainerComponent,
    children: [
      {
        path: '',
        redirectTo: 'dashboard',
        pathMatch: 'full',
      },
      // Identity auth routes (login, register, password reset, email confirmation, user management)
      ...identityAuthRoutes,
      {
        path: 'dashboard',
        pathMatch: 'full',
        canActivate: [authGuard],
        component: OverviewComponent,
        title: $localize`:@@featureContainer-overviewTitle:Overview :: Agenstra`,
      },
      {
        path: 'subscriptions',
        canActivate: [authGuard],
        component: SubscriptionsComponent,
        title: $localize`:@@featureContainer-subscriptionsTitle:Plans :: Agenstra`,
      },
      {
        path: 'invoices',
        canActivate: [authGuard],
        component: InvoicesComponent,
        title: $localize`:@@featureContainer-invoicesTitle:Invoices :: Agenstra`,
      },
      {
        path: 'administration',
        children: [
          {
            path: 'service-types',
            canActivate: [authGuard, billingAdminGuard],
            component: ServiceTypesPageComponent,
            title: $localize`:@@featureContainer-serviceTypesTitle:Service Types :: Agenstra`,
          },
          {
            path: 'service-plans',
            canActivate: [authGuard, billingAdminGuard],
            component: ServicePlansPageComponent,
            title: $localize`:@@featureContainer-servicePlansTitle:Service Plans :: Agenstra`,
          },
          {
            path: 'billing',
            canActivate: [authGuard, billingAdminGuard],
            component: AdminBillingPageComponent,
            title: $localize`:@@featureContainer-adminBillingTitle:Billing :: Agenstra`,
          },
          {
            path: 'customer-profiles',
            canActivate: [authGuard, billingAdminGuard],
            component: AdminCustomerProfilesPageComponent,
            title: $localize`:@@featureContainer-adminProfilesTitle:Billing Profiles :: Agenstra`,
          },
        ],
      },
      {
        path: '**',
        redirectTo: '',
      },
    ],
    providers: [
      ...identityAuthProviders,
      SubscriptionsFacade,
      SubscriptionServerInfoFacade,
      BillingDashboardSocketFacade,
      ServicePlansFacade,
      ServiceTypesFacade,
      InvoicesFacade,
      AdminBillingFacade,
      AdminInvoiceManagerFacade,
      AdminCustomerProfilesFacade,
      BackordersFacade,
      CustomerProfileFacade,
      AvailabilityFacade,
      provideState('subscriptions', subscriptionsReducer),
      provideState('servicePlans', servicePlansReducer),
      provideState('serviceTypes', serviceTypesReducer),
      provideState('invoices', invoicesReducer),
      provideState('adminBilling', adminBillingReducer),
      provideState('adminInvoiceManager', adminInvoiceManagerReducer),
      provideState('adminCustomerProfiles', adminCustomerProfilesReducer),
      provideState('backorders', backordersReducer),
      provideState('customerProfile', customerProfileReducer),
      provideState('availability', availabilityReducer),
      provideState('subscriptionServerInfo', subscriptionServerInfoReducer),
      provideState('billingDashboardSocket', billingDashboardSocketReducer),
      provideEffects({
        loadSubscriptions$,
        loadSubscriptionsBatch$,
        loadSubscription$,
        createSubscription$,
        cancelSubscription$,
        resumeSubscription$,
        loadProviderDetails$,
        loadServiceTypes$,
        loadServiceTypesBatch$,
        loadServiceType$,
        createServiceType$,
        updateServiceType$,
        deleteServiceType$,
        loadServicePlans$,
        loadServicePlansBatch$,
        loadServicePlan$,
        createServicePlan$,
        updateServicePlan$,
        deleteServicePlan$,
        loadInvoices$,
        loadInvoicesSummary$,
        loadOpenOverdueInvoices$,
        createInvoice$,
        reloadInvoicesAfterCreate$,
        loadInvoiceDetails$,
        initiatePaymentRedirect$,
        loadBackorders$,
        loadBackordersBatch$,
        retryBackorder$,
        cancelBackorder$,
        loadCustomerProfile$,
        updateCustomerProfile$,
        checkAvailability$,
        checkAvailabilityAlternatives$,
        previewPricing$,
        loadOverviewServerInfo$,
        startServer$,
        stopServer$,
        restartServer$,
        connectBillingDashboardSocket$,
        disconnectBillingDashboardSocket$,
        connectBillingDashboardSocketFailureFallback$,
        billingDashboardSocketApplicationErrorFallback$,
        loadAdminBillingSummary$,
        billNow$,
        loadAdminOpenOverdue$,
        adminVoidInvoice$,
        adminMarkPaid$,
        adminMarkUnpaid$,
        loadAdminStatisticsSummary$,
        loadAdminStatisticsByProduct$,
        loadAdminAuditLogs$,
        loadAdminInvoiceManager$,
        loadAdminInvoiceManagerBatch$,
        createManualInvoice$,
        updateManualInvoice$,
        issueManualInvoice$,
        deleteManualInvoice$,
        adminInvoiceManagerVoid$,
        adminInvoiceManagerMarkPaid$,
        adminInvoiceManagerMarkUnpaid$,
        loadAdminCustomerProfiles$,
        loadAdminCustomerProfilesBatch$,
        createAdminCustomerProfile$,
        updateAdminCustomerProfile$,
        deleteAdminCustomerProfile$,
      }),
    ],
  },
];
