services:
  frontend-docs-server:
    image: ghcr.io/forepath/agenstra-docs-server:latest
    pull_policy: never
    container_name: docs-server
    environment:
      # Frontend server configuration
      HOST: ${HOST:-0.0.0.0}
      PORT: ${PORT:-4200}
      NODE_ENV: ${NODE_ENV:-production}
      DEFAULT_LOCALE: ${DEFAULT_LOCALE:-en}
    ports:
      - '${PORT:-4200}:${PORT:-4200}'
    networks:
      - docs-network
    restart: unless-stopped

networks:
  docs-network:
    driver: bridge
