export const PAYMENT_PROCESSOR_REGISTRY = Symbol('PAYMENT_PROCESSOR_REGISTRY');
export const BILLING_PROVISIONING_PROVIDER_REGISTRY = Symbol('BILLING_PROVISIONING_PROVIDER_REGISTRY');
export const DECABILL_LOADED_EXTENSIONS = Symbol('DECABILL_LOADED_EXTENSIONS');
