export const AGENT_PROVIDER_REGISTRY = Symbol('AGENT_PROVIDER_REGISTRY');
export const PIPELINE_PROVIDER_REGISTRY = Symbol('PIPELINE_PROVIDER_REGISTRY');
export const CHAT_FILTER_REGISTRY = Symbol('CHAT_FILTER_REGISTRY');
export const PROVISIONING_PROVIDER_REGISTRY = Symbol('PROVISIONING_PROVIDER_REGISTRY');
export const EXTERNAL_IMPORT_PROVIDER_REGISTRY = Symbol('EXTERNAL_IMPORT_PROVIDER_REGISTRY');
export const EMBEDDING_PROVIDER_REGISTRY = Symbol('EMBEDDING_PROVIDER_REGISTRY');
export const AGENSTRA_LOADED_EXTENSIONS = Symbol('AGENSTRA_LOADED_EXTENSIONS');
