import { IDENTITY_NOTIFICATION_EVENTS } from '@forepath/identity/backend';

export const BILLING_NOTIFICATION_EVENTS = [
  ...IDENTITY_NOTIFICATION_EVENTS,
  'invoice.created',
  'invoice.issued',
  'invoice.voided',
  'payment.initiated',
  'payment.succeeded',
  'payment.failed',
  'payment.auto.initiated',
  'payment.auto.retry_scheduled',
  'payment.auto.exhausted',
  'auto_billing.enabled',
  'auto_billing.disabled',
  'payment_method.attached',
  'subscription.created',
  'subscription.updated',
  'subscription.canceled',
  'project.created',
  'project.updated',
  'project.deleted',
  'milestone.created',
  'milestone.updated',
  'milestone.deleted',
  'time_entry.created',
  'time_entry.updated',
  'time_entry.deleted',
  'ticket.created',
  'ticket.updated',
  'ticket.deleted',
  'ticket.comment.created',
  'datev_export.started',
  'datev_export.completed',
  'datev_export.failed',
] as const;

export type BillingNotificationEventType = (typeof BILLING_NOTIFICATION_EVENTS)[number];
