export enum TicketPriority {
  LOW = 'low',
  MEDIUM = 'medium',
  HIGH = 'high',
  CRITICAL = 'critical',
}

export enum TicketStatus {
  DRAFT = 'draft',
  TODO = 'todo',
  IN_PROGRESS = 'in_progress',
  PROTOTYPE = 'prototype',
  DONE = 'done',
  CLOSED = 'closed',
}

/** Request-only; not stored on tickets. Used when creating a root ticket with spec-driven subtasks. */
export enum TicketCreationTemplate {
  EMPTY = 'empty',
  SPECIFICATION = 'specification',
}

export enum TicketActorType {
  HUMAN = 'human',
  AI = 'ai',
  SYSTEM = 'system',
}

/** Stored as varchar(64) in DB; values are stable API contract. */
export enum TicketActionType {
  CREATED = 'CREATED',
  FIELD_UPDATED = 'FIELD_UPDATED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  PRIORITY_CHANGED = 'PRIORITY_CHANGED',
  WORKSPACE_MOVED = 'WORKSPACE_MOVED',
  PARENT_CHANGED = 'PARENT_CHANGED',
  DELETED = 'DELETED',
  COMMENT_ADDED = 'COMMENT_ADDED',
  CONTENT_APPLIED_FROM_AI = 'CONTENT_APPLIED_FROM_AI',
  BODY_GENERATION_STARTED = 'BODY_GENERATION_STARTED',
  PROTOTYPE_PROMPT_GENERATED = 'PROTOTYPE_PROMPT_GENERATED',
  AUTOMATION_CLAIMED = 'AUTOMATION_CLAIMED',
  AUTOMATION_STARTED = 'AUTOMATION_STARTED',
  AUTOMATION_SUCCEEDED = 'AUTOMATION_SUCCEEDED',
  AUTOMATION_FAILED = 'AUTOMATION_FAILED',
  AUTOMATION_TIMED_OUT = 'AUTOMATION_TIMED_OUT',
  AUTOMATION_ESCALATED = 'AUTOMATION_ESCALATED',
  AUTOMATION_REQUEUED = 'AUTOMATION_REQUEUED',
  AUTOMATION_APPROVAL_INVALIDATED = 'AUTOMATION_APPROVAL_INVALIDATED',
  AUTOMATION_CANCELLED = 'AUTOMATION_CANCELLED',
  AUTOMATION_APPROVED = 'AUTOMATION_APPROVED',
  AUTOMATION_UNAPPROVED = 'AUTOMATION_UNAPPROVED',
  AUTOMATION_ELIGIBILITY_CHANGED = 'AUTOMATION_ELIGIBILITY_CHANGED',
  AUTOMATION_APPROVAL_REQUIREMENT_CHANGED = 'AUTOMATION_APPROVAL_REQUIREMENT_CHANGED',
  AUTOMATION_SETTINGS_UPDATED = 'AUTOMATION_SETTINGS_UPDATED',
}
